### PR TITLE
Close meeting programmatically in iOS

### PR DESCRIPTION
**Pull request by jimmyjose-dev**
Added close meeting functionality for iOS with listener support.
usage in Flutter JitsiMeet.closeMeeting();

### CODE REVIEW

**Comment by TBG-FR** [comment]
Nice one ! I'll have to try it, but that was definitely missing, thank you !

**Comment by invitro** [comment]
Can we merge this soon? because we miss iOS part on this feature @tuantvu

**Comment by ducnmhn** [comment]
@Snapworks 

Hi, I have problem with this.

When I call 

`  JitsiMeet.closeMeeting();`

Screen back to my app but Jitsi still running in background, user still in room, camera is running too. I can not turn off this. I am tested with iOS 11.4 and iOS 13.6 on real devices but no luck.

Any ideas how to fix this problem.

**Comment by jimmyjose-dev** [comment]
@ducnmhn How urgently do you need this brother ? willing to wait for the weekend ?
If you really really really want it, I can squeeze in some time today or tomorrow. 
But it has to be more than 2 really :)

**Comment by ducnmhn** [comment]
@Snapworks 

Thank for your support, I can wait for this weekend. There's no rush :100:

**Comment by jimmyjose-dev** [comment]
@ducnmhn I tried at my end and it seems to work fine... do you mind sharing logs or anything else that states otherwise.

**Comment by ducnmhn** [comment]
@Snapworks , Thanks for your support


Logs in debug
`[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: PlatformException(VideoError, Failed to load video: The requested URL was not found on this server., null)
flutter: [GOING TO ROUTE] null
flutter: JitsiMeetingOptions: JitsiMeetingOptions{room: test, serverURL: https://meet.xxxxxxxxxxxx.com, subject: null, token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb250ZXh0Ijp7InVzZXIiOnsiYXZhdGFyIjoiaHR0cHM6Ly9jaGF0LnN0cmVhbWNoYXRsaW5lLmNvbS9hdmF0YXIvb3V0c2lkZXIxNTA_Zm9ybWF0PXBuZyIsIm5hbWUiOiJvdXRzaWRlcjE1MCJ9fSwiYXVkIjoibXlfc2VydmVyMSIsImlzcyI6Im15X3dlYl9jbGllbnQiLCJzdWIiOiJtZWV0LmppdHNpIiwicm9vbSI6IjFfdGVzdGxpdmVfMjZ4dnR2OTJ5cmwiLCJtb2RlcmF0b3IiOnRydWUsImV4cCI6MTU5OTEyNzYwMCwiaWF0IjoxNTk5MTI3MzAwfQ.b-wHXX1ngA3LXm2QYs-IMLY1oTgAbBCKrVoKmlMxxVQ, audioMuted: false, audioOnly: false, videoMuted: false, userDisplayName: null, userEmail: null, iosAppBarRGBAColor :null, featureFlags: {FeatureFlagEnum.ADD_PEOPLE_ENABLED: false, FeatureFlagEnum.CHAT_ENABLED: true, FeatureFlagEnum.INVITE_ENABLED: false, FeatureFlagEnum.MEETING_PASSWORD_ENABLED: false, FeatureFlagEnum.IOS_RECORDING_ENABLED: false, FeatureFlagEnum.LIVE_STREAMING_ENABLED: false, FeatureFlagEnum.RECORDING_ENABLED: false, FeatureFlagEnum.CALENDAR_ENABLED: false} }
flutter: Jitsi Meet - initializing event channel
flutter: Jitsi Meet - broadcast event: {url: https://meet.xxxxxxxxxxxx.com/test, event: onConferenceWillJoin}
flutter: Jitsi Meet - broadcast event: {url: https://meet.xxxxxxxxxxxx.com/test, event: onConferenceJoined}
flutter: [BACK ROUTE] null
flutter: Jitsi Meet - broadcast event: {event: onConferenceTerminated, url: https://meet.xxxxxxxxxxxx.com/test}`

When 
`  Future.delayed(const Duration(seconds: 60), () {
               JitsiMeet.closeMeeting();
            });`

Screen back to my app but Jitsi still running in background, this user not out of room. Other users in room can see this user, camera not off, sound still working too.

This code error

```javascript
_joinMeeting({String room, String token}) async {
    try {
      String server = "https://meet.xxxxxxxxxxxx.com";
      var options = JitsiMeetingOptions()
        ..room = room
        ..serverURL = server
        ..audioOnly = false
        ..audioMuted = false
        ..featureFlags = {
          FeatureFlagEnum.ADD_PEOPLE_ENABLED: false,
          FeatureFlagEnum.CHAT_ENABLED: true,
          FeatureFlagEnum.INVITE_ENABLED: false,
          FeatureFlagEnum.MEETING_PASSWORD_ENABLED: false,
          FeatureFlagEnum.IOS_RECORDING_ENABLED: false,
          FeatureFlagEnum.LIVE_STREAMING_ENABLED: false,
          FeatureFlagEnum.RECORDING_ENABLED: false,
          FeatureFlagEnum.CALENDAR_ENABLED: false,
        }
        ..token = token
        ..videoMuted = false;
      print("JitsiMeetingOptions: $options");
      await JitsiMeet.joinMeeting(
        options,
        listener: JitsiMeetingListener(
          onConferenceWillJoin: ({message}) {
            setState(() {
              status = "Joining Conference !!";
            });
          },
          onConferenceJoined: ({message}) {
            setState(() {
              status = "Joined Conference !!";
            });
            if (widget.roomId != null) {
              joinedMeeting();
            }
            Future.delayed(const Duration(seconds: 60), () {
               JitsiMeet.closeMeeting();
            });
          },
          onConferenceTerminated: ({message}) {
            setState(() {
              status = "Thanks you";
            });
            if (!isBack) {
              isBack = true;
              Navigator.of(context).pop();
            }
          },
          onError: (error) {
            setState(() {
              status = "Something wrong !!";
            });
            if (!isBack) {
              isBack = true;
              Navigator.of(context).pop();
            }
          },
        ),
      );
    } catch (error) {
      print("error: $error");
    }
  }
```

**Comment by ducnmhn** [comment]
> @ducnmhn I tried at my end and it seems to work fine... do you mind sharing logs or anything else that states otherwise.

@Snapworks  Can you reproduce this problem ?

**Comment by jimmyjose-dev** [comment]
@ducnmhn Apologies for ghosting your brother... I will provide a solution in next 2hrs.

**Comment by jimmyjose-dev** [comment]
@ducnmhn I was able to replicate the issue and there are two ways to go about it:
1) I will submit a PR and you can wait for @tuantvu to approve it.
2) While my PR is in queue, I can share with you the fix, in two files you have to write 4 lines of code and it should work.

**Comment by ducnmhn** [comment]
> @ducnmhn I was able to replicate the issue and there are two ways to go about it:
> 
> 1. I will submit a PR and you can wait for @tuantvu to approve it.
> 2. While my PR is in queue, I can share with you the fix, in two files you have to write 4 lines of code and it should work.

Yeah, Thank you so much. I am fixing it now.

**Comment by jimmyjose-dev** [comment]
@ducnmhn Please delete existing app from device/simulator before you build to see the changes.
Do share if the fix works, so @tuantvu may approve the changes.

**Pull request merged**
