### PR TITLE
Migrated to null safety

### LINKED ISSUE #197: [UPGRADE]: Migrate to null safety
## Description
We should migrate this package to null safety.

## Resources
* [How to migrate Dart packages to null safety](https://youtu.be/eBr5tlumwlg)
* [Announcing Dart null safety beta](https://medium.com/dartlang/announcing-dart-null-safety-beta-87610fee6730)

### LINKED ISSUE #221: Flutter null-safety
Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

Error:
jitsi_meet-0.3.0\android\src\main\kotlin\com\gunschu\jitsi_meet\JitsiMeetPlugin.kt:65:37: warning: 'Registrar' is deprecated. Deprecated in Java
        fun registerWith(registrar: Registrar) {                        
                                    ^                             
jitsi_meet-0.3.0\android\src\main\kotlin\com\gunschu\jitsi_meet\JitsiMeetPlugin.kt:154:30: warning: parameter 'call' is never used
    private fun closeMeeting(call: MethodCall, result: Result) {       

jitsi_meet-0.3.0\android\src\main\kotlin\com\gunschu\jitsi_meet\JitsiMeetPluginActivity.kt:43:25: warning: unnecessary safe call on a non-null receiver of type Intent
            when (intent?.action) {
                        ^

### PR DESCRIPTION
**Pull request by nilsreichardt**
## Description
I propose this pull request to [migrate this plugin to null safety](https://dart.dev/null-safety/migration-guide) as it is the way to go now that Flutter 2 has been released.

Here are the changes I introduced:
* Update SDK dependency version to `2.12.0+`
* Run `dart migrate` on existing code to remove unsafe nulls (for the package & example)
* Add a new version (`3.0.0`) to the changelog (as [recommended](https://dart.dev/null-safety/migration-guide#package-version))
* Changed `RaisedButton` to `ElevationButton` in example
* Removed analyzer warnings

Please check everything twice!

## Testing
- [x] Tested it manually on a Android emulator 

### Related tickets
Closes #197

### CODE REVIEW

**Comment by tuantvu** [comment]
@nilsreichardt Thanks for contributing. I should have merged this pull request before merging the Web support PR. Do you mind taking a shot at migrating the latest version of code to null safety? If not, I will attempt also in a few days. Thanks.

**Comment by nilsreichardt** [comment]
@tuantvu I am very busy in the next days 😞 It would be very nice if you can do this 👍

**Comment by tuantvu** [comment]
NP, I'll try to get to it soon.

**Comment by tuantvu** [comment]
Created new branch and pre-release: https://pub.dev/packages/jitsi_meet/versions/4.0.0-nullsafety.0. Closing this PR in favor of another one later. Refer to #197

**Pull request closed without merging**
