### PR TITLE
Example package null-safety migration

### PR DESCRIPTION
**Pull request by sidrao2006**
Merge this PR only after merging #80 

This PR migrates dependent packages to null-safety (except for some transitive dev dependencies)

### CODE REVIEW

**Comment by tuantvu** [comment]
Is sound null-safety still in the dev branch? https://dart.dev/null-safety? I'm guessing you'll  eventually change our pub spec to look like this: `environment: sdk: '>=2.10.0-56.0.dev <3.0.0'`? Do you think they'll be on a stable branch soon?

**Comment by sidrao2006** [comment]
@tuantvu, its on beta...Also the package source code has already been migrated to null-safety it seems. When i was formatting the package for #83, running ` pub upgrade ` migrated all the packages to null safety

**Comment by sidrao2006** [comment]
@tuantvu - Update

Also added a commit fixing the 'too long package description'

**Comment by nilsreichardt** [comment]
Any updates?

**Comment by nilsreichardt** [comment]
I created a PR where I migrated the package and the example: #217

**Pull request closed without merging**
