### PR TITLE
Refactored Feature Flags + added new

### LINKED ISSUE #20: Reduce video Quality
How can I reduce video Quality using jitsi

### PR DESCRIPTION
**Pull request by jimmyjose-dev**
1. Refactored feature flag code to accommodate new ones. 
2. Modified main.dart, with new example code.
3. Raised Flutter deployment target for iOS from 8.0 to 11.0.
4. Updated Xcode project settings to build faster.

Added feature flag support for:
1. Flag for local and (maximum) remote video resolution and overrides server configuration.
Supports 180p, 360p, 480p, 720p

2. Flag for conference timer.

3. Flag for server URL change.

4. Flag for video share button .

5. Flag for kick out button.

Sample usage of feature flag

```
FeatureFlag featureFlag = FeatureFlag();
featureFlag.welcomePageEnabled = false;
featureFlag.resolution = FeatureFlagVideoResolution.MD_RESOLUTION;

var options = JitsiMeetingOptions()
        ..room = roomText.text
        ..serverURL = serverUrl
        ..subject = subjectText.text
        ..userDisplayName = nameText.text
        ..userEmail = emailText.text
        ..audioOnly = isAudioOnly
        ..audioMuted = isAudioMuted
        ..videoMuted = isVideoMuted
        ..featureFlag = featureFlag;
```

Supported values for resolution
For video resolution at 180p use LD_RESOLUTION
For video resolution at 360p use MD_RESOLUTION
For video resolution at 480p (SD) use SD_RESOLUTION
For video resolution at 720p (HD) use HD_RESOLUTION

Closes #20

### CODE REVIEW

**Review by tuantvu — APPROVED** [review]

**Comment by tuantvu** [comment]
@Snapworks @buzzwin  The change to feature flags from enum map to class is a breaking change for older clients. I'm bumping version number to 2.0.0. Sound good?

**Comment by jimmyjose-dev** [comment]
@tuantvu changes to be done in the readme file too.. will you be doing that ?

**Comment by tuantvu** [comment]
Feel free to update the readme before I publish

**Comment by jimmyjose-dev** [comment]
I can work on it tomorrow..

**Comment by TBG-FR** [comment]
Great work ! I'll try this soon

**Comment by jimmyjose-dev** [comment]
Great to hear from you 😃 .. hope you are keeping well.

**Comment by TBG-FR** [comment]
I'm doing well, but as you've seen I couldn't find enough time to work on Jitsi Meet again, lots of work to do !
Hope you're doing well too, stay stafe out there !

**Pull request merged**
