### PR TITLE
Resolve Dependency

### LINKED ISSUE #18: Update minSDK to 21
Hi, I've searched around and [found](https://community.jitsi.org/t/jitsi-meet-android-sdk-level-api-21/21496) that there's a solution to decrease min sdk version to 21. This implementation will have a really good impact, as phones on Android 5 and 6 are still widely used. 
P.s. really great plugin, thanks for your work!

### LINKED ISSUE #29: Update Android Jitsi SDK to 2.8.1
Currently this package is using `2.5.1`. But meanwhile `2.8.2` is already available.

### PR DESCRIPTION
**Pull request by chandrabezzo**
I was change change :
- Minimum version to 21
- Upgrade build tools gradle version
- Upgrader gradle wrapper version
- Add JavaVersion compile to 1.8
- Upgrade jitsi_meet version to 2.8.2
- Resolve serverURL to join meeting
- Closes #29 
- Closes #18

### CODE REVIEW

**Comment by nilsreichardt** [comment]
This PR would also resolve #29 👍 Can you include `Closes #29` in your PR description?

**Comment by nilsreichardt** [comment]
Any ideas why Jitsi doesn't translate the buttons? Without this PR every button is translated into German (device language).

image

**Comment by chandrabezzo** [comment]
If you want to change language of jitsi meet layout, you must change code of sdk in jitsi meet using react native.

**Comment by TBG-FR** [comment]
@AndroidNils As I said in #29 , the language issue is a bug from the SDK version `2.8.2` (this is why we should aim for `2.8.0` or wait for the next version)

**Comment by nilsreichardt** [comment]
@TBG-FR I think we should use `2.8.0` and create a new PR, if `2.8.2` is fixed

**Comment by chandrabezzo** [comment]
@TBG-FR @AndroidNils I think after this PR merged, you can resolve about jitsi version

**Review by ghost — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Pull request merged**
