### PR TITLE
add userAvatarURL

### PR DESCRIPTION
**Pull request by NVQuan**
add property userAvatarURL and add an avatar in IOS

### CODE REVIEW

**Comment by tuantvu** [comment]
Hi, I've tried these settings with jitsi meet sdk before, but never got it working. I think the URL needs to be from an avatar service right? Could you provide a screenshot and instructions on how to use this field in this comment? The ReadMe will also need to be updated to explain the above.

**Comment by jimmyjose-dev** [comment]
> Hi, I've tried these settings with jitsi meet sdk before, but never got it working. I think the URL needs to be from an avatar service right? Could you provide a screenshot and instructions on how to use this field in this comment? The ReadMe will also need to be updated to explain the above.

var options = JitsiMeetingOptions()
        ..room = roomText.text
        ..serverURL = serverUrl
        ..subject = subjectText.text
        ..userDisplayName = nameText.text
        ..userEmail = emailText.text
        ..audioOnly = isAudioOnly
        ..audioMuted = isAudioMuted
        ..videoMuted = isVideoMuted
        **..userAvatarURL =
            "https://images.pexels.com/photos/4026110/pexels-photo-4026110.jpeg"**
        ..featureFlags.addAll(featureFlags);

**Comment by NVQuan** [comment]
> Hi, I've tried these settings with jitsi meet sdk before, but never got it working. I think the URL needs to be from an avatar service right? Could you provide a screenshot and instructions on how to use this field in this comment? The ReadMe will also need to be updated to explain the above.

Image: [https://github.com/NVQuan/jitsi_meet/blob/image/image.jpg](url)

var options = JitsiMeetingOptions()
..userAvatarURL = "url";

**Comment by jimmyjose-dev** [comment]
@NVQuan It will be better if you can keep only related features in a single pull request... disabling lock screen should be shared separately.

@tuantvu I have tested and the code works for both Android and iOS.

**Comment by tuantvu** [comment]
@Snapworks thanks! Feel free to merge. I can update the readme and publish a new feature after work. @NVQuan Thanks for contributing.

**Pull request merged**
